name: CREATE IMAGES

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - '.devcontainer/**'
      - '.docs/**'
      - '.github/oldsrc/**'
      - '.github/HELP.md'
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches: 
      - master 

env:
  HELM_EXPERIMENTAL_OCI: 1 #enable OCI support
  GITVERSION_FILE: .github/gitversion/GitVersion.yml
  REPOSITORY: ghcr.io/jnnkrdb/orasul
  DOCKERFILE: ./Dockerfile
  VERSION_FILE: ./VERSION
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
          
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
          configFilePath: ${{ env.GITVERSION_FILE }}

      - id: version
        run: echo "semver=${{ steps.gitversion.outputs.semVer }}" >> $GITHUB_OUTPUT

  build:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: bash-version
        run: |
          echo ${{ needs.version.outputs.semver }} > ${{ env.VERSION_FILE }}
          echo $(cat ${{ env.VERSION_FILE }})

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHP_TOKEN }}

      - name: Build Image Without Push
        uses: docker/build-push-action@v5
        if: github.event_name == 'pull_request'
        with:
          context: "."
          file: ${{ env.DOCKERFILE }}
          push: false
      
      - name: Build Image With Push
        uses: docker/build-push-action@v5
        with:
          context: "."
          file: ${{ env.DOCKERFILE }}
          tags: ${{ env.REPOSITORY }}:${{ env.BRANCH_NAME }}
          push: true

      - name: Build Image With Push
        uses: docker/build-push-action@v5
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
        with:
          context: "."
          file: ${{ env.DOCKERFILE }}
          tags: ${{ env.REPOSITORY }}:${{ needs.version.outputs.semver }}
          push: true
